### ISSUE TITLE
.yardmanrc is required

### ISSUE THREAD

**Issue by MiniGod** [agirorn/yardman#1]
The readme implies that the `.yardmanrc` file is optional, yet if I run this without the file present I get the following error:

```
Error: ENOENT: no such file or directory, open '.yardmanrc'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at fs.readFileSync (fs.js:509:33)
    at readRcfile (/home/kristjan/n/lib/node_modules/yardman/lib/cli/read.js:6:5)
    at cli (/home/kristjan/n/lib/node_modules/yardman/lib/cli/index.js:6:32)
```

**Comment by agirorn** [comment]
Do you want to make a PR to fixing that?
